### ISSUE TITLE
No Query or Key Found when using nn.TransformerEncoderLayer

### ISSUE THREAD

**Issue by USBskycrafts** [zyushun/Adam-mini#30]
there is a warning says "=====>>>  Warning by Adam-mini: No Query or Key found. If you are training Transformers......".

The existence of Key and Query is judged by  `self.wqk_names = {"k_proj.weight", "q_proj.weight", "wq.weight", "wk.weight"}`, and there is only a `self_attn.in_proj_weight` in the `nn.TransformerEncoderLayer`. So I think more works need to be done to solve this situation.

**Comment by zyushun** [comment]
Hi @USBskycrafts , it seems that you you are using "fused attention" implementation, which merges q,k, v as a whole. 
We do not support "fused attention" for now, but here is a simple twist: 

1. use the lastest version of Adam-mini  (version 1.0.4) in  PyPI. Try :pip install adam-mini" again if you are using the old version.
2. In the optimizer, change: self.mlp_names = {} to self.mlp_names = {"self_attn.in_proj_weight"}.

This operation will calculate vmean by the output dimension (or equivalently, by row ) of the the merged QKV matrix.  This will cause a slight mismatch with our original design (calculate vmean by head of Q and K), but I guess the performance would  be similar.

Please have a try and see if it helps.

**Comment by buttercutter** [comment]
@zyushun : I tried the following, but still not helping.  Could you advise ?

```python
optimizer_denoiser.mlp_names = {"self_attn.in_proj_weight"}
optimizer_denoiser.output_names.add('projection.weight')  # actual output layer name

for i in range(num_layers):
    optimizer_denoiser.wqk_names.add(f'transformer_encoder.layers.{i}.self_attn.in_proj_weight')  # For query, key, and value combined
    optimizer_denoiser.wqk_names.add(f'transformer_decoder.layers.{i}.self_attn.in_proj_weight')  # Another example for decoder
    optimizer_denoiser.wqk_names.add(f'transformer_decoder.layers.{i}.multihead_attn.in_proj_weight')  # Another example for decoder
```

```
Adam-mini found the param block with name: embedding.weight
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_weight
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_bias
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.weight
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.bias
Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.weight
Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.bias
Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.weight
Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.bias
Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.weight
Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.bias
Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.weight
Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.bias
Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.in_proj_weight
Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.in_proj_bias
Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.out_proj.weight
Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.out_proj.bias
Adam-mini found the param block with name: transformer_encoder.layers.1.linear1.weight
Adam-mini found the param block with name: transformer_encoder.layers.1.linear1.bias
Adam-mini found the param block with name: transformer_encoder.layers.1.linear2.weight
Adam-mini found the param block with name: transformer_encoder.layers.1.linear2.bias
Adam-mini found the param block with name: transformer_encoder.layers.1.norm1.weight
Adam-mini found the param block with name: transformer_encoder.layers.1.norm1.bias
Adam-mini found the param block with name: transformer_encoder.layers.1.norm2.weight
Adam-mini found the param block with name: transformer_encoder.layers.1.norm2.bias
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_weight
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_bias
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.weight
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.bias
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_weight
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_bias
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.weight
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.bias
Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.weight
Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.bias
Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.weight
Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.bias
Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.weight
Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.bias
Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.weight
Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.bias
Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.weight
Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.bias
Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.in_proj_weight
Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.in_proj_bias
Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.out_proj.weight
Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.out_proj.bias
Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.in_proj_weight
Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.in_proj_bias
Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.out_proj.weight
Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.out_proj.bias
Adam-mini found the param block with name: transformer_decoder.layers.1.linear1.weight
Adam-mini found the param block with name: transformer_decoder.layers.1.linear1.bias
Adam-mini found the param block with name: transformer_decoder.layers.1.linear2.weight
Adam-mini found the param block with name: transformer_decoder.layers.1.linear2.bias
Adam-mini found the param block with name: transformer_decoder.layers.1.norm1.weight
Adam-mini found the param block with name: transformer_decoder.layers.1.norm1.bias
Adam-mini found the param block with name: transformer_decoder.layers.1.norm2.weight
Adam-mini found the param block with name: transformer_decoder.layers.1.norm2.bias
Adam-mini found the param block with name: transformer_decoder.layers.1.norm3.weight
Adam-mini found the param block with name: transformer_decoder.layers.1.norm3.bias
Adam-mini found the param block with name: norm.weight
Adam-mini found the param block with name: norm.bias
Adam-mini found the param block with name: projection.bias
Adam-mini found the param block with name: denoise_head.0.bias
Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original0
Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original1
Adam-mini found 1 embedding layers, 0 output layers, 0 Querys, Keys, and Values.
```

**Comment by zyushun** [comment]
Hi @buttercutter . Thanks for the update. Please try the following.

1. run "pip install adam-mini" again. This will install the latest version of Adam-mini (version 1.0.5) in PyPI. Note that it will be  version 1.0.5, not version 1.0.4 as you previously used.

2. run the following 
```
        optimizer = Adam_mini(
                    named_parameters = model.named_parameters(),
                    lr = lr,
                    betas = (beta1,beta2),
                    eps = eps,
                    weight_decay = weight_decay,
                    dim = model_config.dim,
                    n_heads = model_config.n_heads,
                    n_kv_heads = model_config.n_kv_heads,
                    )
           optimizer.mlp_names.add("attn") 
           optimizer.mlp_names.add("linear") 
```


You will still receive the log "Adam-mini found ...., 0 Querys, Keys, and Values." But it is okay you can ignore this.


Please try :)

**Comment by zyushun** [comment]
@buttercutter  I just realize that you are already using v1.0.5, so you don't need to re-install again. Just add the following two lines after the optimizer.


```
optimizer.mlp_names.add("attn") 
optimizer.mlp_names.add("linear") 
```


Please try :)

**Comment by buttercutter** [comment]
@zyushun : I added those two lines, then I got this strange error.

```
   File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/adam_mini/adam_mini.py", line 257, in step
     state["vmean"] = torch.zeros_like(state["m"][0:state["neuron_per_gpu"], 0:1], memory_format=torch.preserve_format)
                                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 IndexError: too many indices for tensor of dimension 1
```

**Comment by zyushun** [comment]
Hi, @buttercutter . Good to know this...
This error is because the weight matrices (and the associated gradient matrices) in your codebase are all stretched as long vectors. This is a corner case that we are aware of, but we find it is relatively rare to occur.  Our current implementation assumes all weight matrices are matrices rather than vectors, so we do not support this case. Sorry for the inconvenience.


A simple twist is to remove these lines. 


```
optimizer.mlp_names.add("attn")  # remove this line 
optimizer.mlp_names.add("linear")  # remove this line
```

By removing these two lines, Adam-mini will use a single learning rate for each block under pytorch default partition (except for the embedding and output layers, where it will use Adam). There is no guarantee that this would perform well but you can have a try. Usually, it does not work well for pre-training but it can work for finetuning.

**Comment by buttercutter** [comment]
@zyushun : Thanks and I really appreciate your prompt reply.

So far, my model training run memory consumption does not decrease.

> You will still receive the log "Adam-mini found ...., 0 Querys, Keys, and Values." But it is okay you can ignore this.

```python
optimizer_denoiser.mlp_names = {"self_attn.in_proj_weight"}
optimizer_denoiser.output_names.add('embedding.weight')  # actual output layer name, projection layer is using weight-tying with embedding layer

for i in range(num_layers):
    optimizer_denoiser.wqk_names.add(f'transformer_encoder.layers.{i}.self_attn.in_proj_weight')  # For query, key, and value combined
    optimizer_denoiser.wqk_names.add(f'transformer_decoder.layers.{i}.self_attn.in_proj_weight')  # Another example for decoder
    optimizer_denoiser.wqk_names.add(f'transformer_decoder.layers.{i}.multihead_attn.in_proj_weight')  # Another example for decoder
```

**Comment by buttercutter** [comment]
@zyushun :  Thanks again for your prompt response.

> By removing these two lines, Adam-mini will use a single learning rate for each block under pytorch default partition (except for the embedding and output layers, where it will use Adam).

Noted.  I increase the model internal dimension size for both the encoders and decoders, yet still seeing no decreasing memory consumption trend. 

> Did you use any other orthogonalization tricks to AdamW, like quantization or cpu-offload? Or are you using PagedAdam (which will use quantization)?

No.  By the way, I am using MPS backend.

**Comment by zyushun** [comment]
Hi @buttercutter ,  How large is your model? One possible reason: your model is too small so the embedding + output layer takes the major proportion of memory.

**Comment by zyushun** [comment]
@buttercutter  Yes! We have developed a new version of Adam-mini (would be v.1.0.6) and it will also cut down the memory for embedding & output layers to almost 0. We will also update the paper soon accordingly. 

I will keep you noticed once we updated v.1.0.6. 😄

**Comment by buttercutter** [comment]
@zyushun : I noticed that Adam-mini version is currently at v.1.1.0

For the new version, could I skip the following warnings before I check the traceback error ?

```
 Adam-mini found 0 embedding layers, 0 output layers; 0 Querys and Keys;  0 Values;  0 attn_proj;  0 MLPs;
 =====>>> Warning by Adam-mini: No embedding layer found. If you are training Transformers, please check the name of your embedding layer and manually add them to 'self.embd_names' of Adam-mini. You can do this by  adding an additional line of code: optimizer.embd_names.add('the keywords in the name of your embedding layer').
 =====>>> Warning by Adam-mini: No output layer found. If you are training Transformers (without weight-tying), please check the name of your output layer and manually add them to 'self.output_names' of Adam-mini.  You can do this by adding an additional line of code: optimizer.output_names.add('the keywords in the  name of your output layer').  Please ignore this warning if you are using weight-tying.
 =====>>>  Warning by Adam-mini: No Query or Key found. If you are training Transformers, please check the name of your Query and Key in attention blocks and manually add them to 'self.wqk_names' of Adam-mini. You  can do this by adding two additional lines of code: optimizer.wqk_names.add('the keywords in the  name of your Query' ); optimizer.wqk_names.add('the keywords in the  name of your Key').
 =====>>>  Warning by Adam-mini: No Value found. If you are training Transformers, please check the name of your Value in attention blocks and manually add them to 'self.wv_names' of Adam-mini. You can do this by   adding an additional lines of code: optimizer.wv_names.add('the keywords in the  name of your Value' ).
 =====>>>  Warning by Adam-mini: No attn_proj found. If you are training Transformers, please check the name of your attn_proj in attention blocks and manually add them to 'self.attn_proj_names' of Adam-mini. You   can do this by adding an additional lines of code: optimizer.attn_proj_names.add('the keywords in the  name of your attn_proj' ).
 =====>>>  Warning by Adam-mini: No MLP found. If you are training Transformers, please check the name of your MLP in attention blocks and manually add them to 'self.mlp_names' of Adam-mini. You can do this by      adding an additional lines of code: optimizer.attn_proj_names.add('the keywords in the  name of your MLP' ).
 =====>>>  Warning by Adam-mini: you are using default PyTorch partition for Adam-mini. It can cause training instability on large-scale Transformers.
```

**Comment by zyushun** [comment]
Hi @buttercutter, yes, we have updated 1.1.0 version of Adam-mini, which saves  memory for the embedding & output layers.  
Please add the following lines after creating the optimizer.

```
optimizer.embd_names.add('embedding') #add the keyword of your embedding layer
optimizer.output_names.add('head') #add the keyword of your output layer
```

Note that we still assume embedding & output layers are matrices instead of long vectors. So it might raise error if your codebase will automatically reshape the embedding & output parameters to vectors.  If this is the case, then you can put embedding and output layer to `adam_blocks` and use Adam for them (same as before, and there will be no significant memory drop for your small model).

```
optimizer.adam_block_names.add('embedding') #add the keyword of your embedding layer
optimizer.adam_block_names.add('head') #add the keyword of your output layer
```

We will try to support the case where "weight matrices are stretched as long vectors" in future versions, perhaps in v.1.1.1.

**Comment by buttercutter** [comment]
Hi @zyushun , sorry for overwhelming you with a lot of technical questions.  

I had added the following naming instantiation schemes to help Adam_Mini locates the layers, but they are not able to do so according to the warning log.

```python
optimizer_ebm.embd_names.add('embedding') # add the keyword of the embedding layer
optimizer_ebm.output_names.add('denoise_head') # output layer of EBM model is not using projection layer
optimizer_denoiser.embd_names.add('embedding') # add the keyword of the embedding layer
optimizer_denoiser.output_names.add('projection') # projection layer is using weight-tying with embedding layer

optimizer_ebm.mlp_names = {"self_attn"}
optimizer_denoiser.mlp_names = {"self_attn"}

optimizer_ebm.mlp_names.add("attn")
optimizer_ebm.mlp_names.add("linear")
optimizer_denoiser.mlp_names.add("attn")
optimizer_denoiser.mlp_names.add("linear")

optimizer_denoiser.wqk_names.add("self_attn")  # For query, key, and value combined
optimizer_denoiser.wqk_names.add("multihead_attn")
```

```
Adam-mini found the param block with name: embedding.weight torch.Size([30522, 32])
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_weight torch.Size([96, 32])
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_bias torch.Size([96])
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.weight torch.Size([32, 32])
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.bias torch.Size([32])
Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.weight torch.Size([32, 32])
Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.bias torch.Size([32])
Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.weight torch.Size([32, 32])
Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.bias torch.Size([32])
Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.weight torch.Size([32])
Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.bias torch.Size([32])
Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.weight torch.Size([32])
Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.bias torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_weight torch.Size([96, 32])
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_bias torch.Size([96])
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.weight torch.Size([32, 32])
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.bias torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_weight torch.Size([96, 32])
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_bias torch.Size([96])
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.weight torch.Size([32, 32])
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.bias torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.weight torch.Size([32, 32])
Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.bias torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.weight torch.Size([32, 32])
Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.bias torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.weight torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.bias torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.weight torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.bias torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.weight torch.Size([32])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.bias torch.Size([32])
Adam-mini found the param block with name: norm.weight torch.Size([32])
Adam-mini found the param block with name: norm.bias torch.Size([32])
Adam-mini found the param block with name: projection.bias torch.Size([30522])
Adam-mini found the param block with name: denoise_head.0.bias torch.Size([32])
Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original0 torch.Size([32, 1, 1])
Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original1 torch.Size([32, 32, 3])
Adam-mini found the param block with name: embedding.weight torch.Size([30522, 128])
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_weight torch.Size([384, 128])
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_bias torch.Size([384])
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.weight torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.weight torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.in_proj_weight torch.Size([384, 128])
Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.in_proj_bias torch.Size([384])
Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.out_proj.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.out_proj.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.1.linear1.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_encoder.layers.1.linear1.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.1.linear2.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_encoder.layers.1.linear2.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.1.norm1.weight torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.1.norm1.bias torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.1.norm2.weight torch.Size([128])
Adam-mini found the param block with name: transformer_encoder.layers.1.norm2.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_weight torch.Size([384, 128])
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_bias torch.Size([384])
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_weight torch.Size([384, 128])
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_bias torch.Size([384])
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.weight torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.weight torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.weight torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.in_proj_weight torch.Size([384, 128])
Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.in_proj_bias torch.Size([384])
Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.out_proj.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.out_proj.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.in_proj_weight torch.Size([384, 128])
Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.in_proj_bias torch.Size([384])
Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.out_proj.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.out_proj.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.linear1.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_decoder.layers.1.linear1.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.linear2.weight torch.Size([128, 128])
Adam-mini found the param block with name: transformer_decoder.layers.1.linear2.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.norm1.weight torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.norm1.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.norm2.weight torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.norm2.bias torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.norm3.weight torch.Size([128])
Adam-mini found the param block with name: transformer_decoder.layers.1.norm3.bias torch.Size([128])
Adam-mini found the param block with name: norm.weight torch.Size([128])
Adam-mini found the param block with name: norm.bias torch.Size([128])
Adam-mini found the param block with name: projection.bias torch.Size([30522])
Adam-mini found the param block with name: denoise_head.0.bias torch.Size([128])
Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original0 torch.Size([128, 1, 1])
Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original1 torch.Size([128, 128, 3])
Adam-mini found 0 embedding layers, 0 output layers; 0 Querys and Keys;  0 Values;  0 attn_proj;  0 MLPs;
=====>>> Warning by Adam-mini: No embedding layer found. If you are training Transformers, please check the name of your embedding layer and manually add them to 'self.embd_names' of Adam-mini. You can do this by adding an additional line of code: optimizer.embd_names.add('the keywords in the name of your embedding layer'). 
=====>>> Warning by Adam-mini: No output layer found. If you are training Transformers (without weight-tying), please check the name of your output layer and manually add them to 'self.output_names' of Adam-mini. You can do this by adding an additional line of code: optimizer.output_names.add('the keywords in the  name of your output layer').  Please ignore this warning if you are using weight-tying.
=====>>>  Warning by Adam-mini: No Query or Key found. If you are training Transformers, please check the name of your Query and Key in attention blocks and manually add them to 'self.wqk_names' of Adam-mini. You can do this by adding two additional lines of code: optimizer.wqk_names.add('the keywords in the  name of your Query' ); optimizer.wqk_names.add('the keywords in the  name of your Key'). 
=====>>>  Warning by Adam-mini: No Value found. If you are training Transformers, please check the name of your Value in attention blocks and manually add them to 'self.wv_names' of Adam-mini. You can do this by adding an additional lines of code: optimizer.wv_names.add('the keywords in the  name of your Value' ). 
=====>>>  Warning by Adam-mini: No attn_proj found. If you are training Transformers, please check the name of your attn_proj in attention blocks and manually add them to 'self.attn_proj_names' of Adam-mini. You can do this by adding an additional lines of code: optimizer.attn_proj_names.add('the keywords in the  name of your attn_proj' ). 
=====>>>  Warning by Adam-mini: No MLP found. If you are training Transformers, please check the name of your MLP in attention blocks and manually add them to 'self.mlp_names' of Adam-mini. You can do this by adding an additional lines of code: optimizer.attn_proj_names.add('the keywords in the  name of your MLP' ). 
=====>>>  Warning by Adam-mini: you are using default PyTorch partition for Adam-mini. It can cause training instability on large-scale Transformers.
```

**Comment by Sun2018421** [comment]
> Hi @zyushun , sorry for overwhelming you with a lot of technical questions.
> 
> I had added the following naming instantiation schemes to help Adam_Mini locates the layers, but they are not able to do so according to the warning log.
> 
> ```python
> optimizer_ebm.embd_names.add('embedding') # add the keyword of the embedding layer
> optimizer_ebm.output_names.add('denoise_head') # output layer of EBM model is not using projection layer
> optimizer_denoiser.embd_names.add('embedding') # add the keyword of the embedding layer
> optimizer_denoiser.output_names.add('projection') # projection layer is using weight-tying with embedding layer
> 
> optimizer_ebm.mlp_names = {"self_attn"}
> optimizer_denoiser.mlp_names = {"self_attn"}
> 
> optimizer_ebm.mlp_names.add("attn")
> optimizer_ebm.mlp_names.add("linear")
> optimizer_denoiser.mlp_names.add("attn")
> optimizer_denoiser.mlp_names.add("linear")
> 
> optimizer_denoiser.wqk_names.add("self_attn")  # For query, key, and value combined
> optimizer_denoiser.wqk_names.add("multihead_attn")
> ```
> 
> ```
> Adam-mini found the param block with name: embedding.weight torch.Size([30522, 32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_weight torch.Size([96, 32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_bias torch.Size([96])
> Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.weight torch.Size([32, 32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.weight torch.Size([32, 32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.weight torch.Size([32, 32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.weight torch.Size([32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.weight torch.Size([32])
> Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_weight torch.Size([96, 32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_bias torch.Size([96])
> Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.weight torch.Size([32, 32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_weight torch.Size([96, 32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_bias torch.Size([96])
> Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.weight torch.Size([32, 32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.weight torch.Size([32, 32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.weight torch.Size([32, 32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.weight torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.weight torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.bias torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.weight torch.Size([32])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.bias torch.Size([32])
> Adam-mini found the param block with name: norm.weight torch.Size([32])
> Adam-mini found the param block with name: norm.bias torch.Size([32])
> Adam-mini found the param block with name: projection.bias torch.Size([30522])
> Adam-mini found the param block with name: denoise_head.0.bias torch.Size([32])
> Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original0 torch.Size([32, 1, 1])
> Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original1 torch.Size([32, 32, 3])
> Adam-mini found the param block with name: embedding.weight torch.Size([30522, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_weight torch.Size([384, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.in_proj_bias torch.Size([384])
> Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.self_attn.out_proj.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.linear1.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.linear2.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.norm1.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.0.norm2.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.in_proj_weight torch.Size([384, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.in_proj_bias torch.Size([384])
> Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.out_proj.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.self_attn.out_proj.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.linear1.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.linear1.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.linear2.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.linear2.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.norm1.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.norm1.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.norm2.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_encoder.layers.1.norm2.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_weight torch.Size([384, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.in_proj_bias torch.Size([384])
> Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.self_attn.out_proj.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_weight torch.Size([384, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.in_proj_bias torch.Size([384])
> Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.multihead_attn.out_proj.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.linear1.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.linear2.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm1.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm2.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.0.norm3.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.in_proj_weight torch.Size([384, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.in_proj_bias torch.Size([384])
> Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.out_proj.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.self_attn.out_proj.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.in_proj_weight torch.Size([384, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.in_proj_bias torch.Size([384])
> Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.out_proj.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.multihead_attn.out_proj.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.linear1.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.linear1.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.linear2.weight torch.Size([128, 128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.linear2.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.norm1.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.norm1.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.norm2.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.norm2.bias torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.norm3.weight torch.Size([128])
> Adam-mini found the param block with name: transformer_decoder.layers.1.norm3.bias torch.Size([128])
> Adam-mini found the param block with name: norm.weight torch.Size([128])
> Adam-mini found the param block with name: norm.bias torch.Size([128])
> Adam-mini found the param block with name: projection.bias torch.Size([30522])
> Adam-mini found the param block with name: denoise_head.0.bias torch.Size([128])
> Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original0 torch.Size([128, 1, 1])
> Adam-mini found the param block with name: denoise_head.0.parametrizations.weight.original1 torch.Size([128, 128, 3])
> Adam-mini found 0 embedding layers, 0 output layers; 0 Querys and Keys;  0 Values;  0 attn_proj;  0 MLPs;
> =====>>> Warning by Adam-mini: No embedding layer found. If you are training Transformers, please check the name of your embedding layer and manually add them to 'self.embd_names' of Adam-mini. You can do this by adding an additional line of code: optimizer.embd_names.add('the keywords in the name of your embedding layer'). 
> =====>>> Warning by Adam-mini: No output layer found. If you are training Transformers (without weight-tying), please check the name of your output layer and manually add them to 'self.output_names' of Adam-mini. You can do this by adding an additional line of code: optimizer.output_names.add('the keywords in the  name of your output layer').  Please ignore this warning if you are using weight-tying.
> =====>>>  Warning by Adam-mini: No Query or Key found. If you are training Transformers, please check the name of your Query and Key in attention blocks and manually add them to 'self.wqk_names' of Adam-mini. You can do this by adding two additional lines of code: optimizer.wqk_names.add('the keywords in the  name of your Query' ); optimizer.wqk_names.add('the keywords in the  name of your Key'). 
> =====>>>  Warning by Adam-mini: No Value found. If you are training Transformers, please check the name of your Value in attention blocks and manually add them to 'self.wv_names' of Adam-mini. You can do this by adding an additional lines of code: optimizer.wv_names.add('the keywords in the  name of your Value' ). 
> =====>>>  Warning by Adam-mini: No attn_proj found. If you are training Transformers, please check the name of your attn_proj in attention blocks and manually add them to 'self.attn_proj_names' of Adam-mini. You can do this by adding an additional lines of code: optimizer.attn_proj_names.add('the keywords in the  name of your attn_proj' ). 
> =====>>>  Warning by Adam-mini: No MLP found. If you are training Transformers, please check the name of your MLP in attention blocks and manually add them to 'self.mlp_names' of Adam-mini. You can do this by adding an additional lines of code: optimizer.attn_proj_names.add('the keywords in the  name of your MLP' ). 
> =====>>>  Warning by Adam-mini: you are using default PyTorch partition for Adam-mini. It can cause training instability on large-scale Transformers.
> ```

I met the same issue, when i try to run run_gpt2.sh (gpt2_small)

**Comment by Sun2018421** [comment]
I thought the issue came from the self.named_parameters in the class  Adam-mini. Because it's a generator, it will have no elements after we have a loop in the __init__ function. So the warning will appear the second time call on this generator in the count_block function.  The problem was solved when I changed the code "self.named_parameters = list(named_parameters)" and "for param_name, param in self.named_parameters:" in __init__ function. I hope this was helpful.

**Comment by zyushun** [comment]
@Sun2018421 Hi! Thanks for the update.

Sorry for the late response since I am traveling recently. I will get back to your question as soon as I am settled.

Yushun

**Comment by Sun2018421** [comment]
@zyushun Thank you very much for your reply and wish you a pleasant trip :)

**Comment by zyushun** [comment]
Hi @Sun2018421 , we have updated Adam-mini to v.1.1.1 and this issue is fixed.  Please pip uninstall and install adam-mini again.

Thanks a lot for mentioning this issue!  We have acknowledged your help in [readme](https://github.com/zyushun/Adam-mini).

**Comment by buttercutter** [comment]
@zyushun Thanks for getting it to `v1.1.1`

I am still getting the following runtime error with this latest version.  It seems that the [previous error](https://github.com/zyushun/Adam-mini/issues/30#issuecomment-2404931804) popped up again ?

```
   File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/adam_mini/adam_mini.py", line 303, in step
     state["vmean"] = torch.zeros_like(state["m"][0:state["neuron_per_gpu"], 0:1],
                                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 IndexError: too many indices for tensor of dimension 1
```

**Comment by nighting0le01** [comment]
@zyushun @buttercutter  i get something like 

```
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/adam_mini/adam_mini.py", line 303, in step
     state["vmean"] = torch.zeros_like(state["m"][0:state["neuron_per_gpu"], 0:1],
                                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 IndexError: too many indices for tensor of dimension 1
```

any sollution

**Comment by nighting0le01** [comment]
i think with FSDP and tensor-paralllel you will get 

```
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/adam_mini/adam_mini.py", line 303, in step
     state["vmean"] = torch.zeros_like(state["m"][0:state["neuron_per_gpu"], 0:1],
                                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 IndexError: too many indices for tensor of dimension 1
```

**Comment by nighting0le01** [comment]
> Hi, @buttercutter . Good to know this... This error is because the weight matrices (and the associated gradient matrices) in your codebase are all stretched as long vectors. This is a corner case that we are aware of, but we find it is relatively rare to occur. Our current implementation assumes all weight matrices are matrices rather than vectors, so we do not support this case. Sorry for the inconvenience.
> 
> A simple twist is to remove these lines.
> 
> ```
> optimizer.mlp_names.add("attn")  # remove this line 
> optimizer.mlp_names.add("linear")  # remove this line
> ```
> 
> By removing these two lines, Adam-mini will use a single learning rate for each block under pytorch default partition (except for the embedding and output layers, where it will use Adam). There is no guarantee that this would perform well but you can have a try. Usually, it does not work well for pre-training but it can work for finetuning.

@buttercutter @zyushun @awgu  how can it work with torchtitan Tensorparalllel and FSDP2 if that is the case

**Comment by animemory** [comment]
> too many indices for

any solution here~
